Первый вариант задания "Камень судьбы"
htmlacademy-yii/1806383-task-force-1 pull request #2
Opened 2021-06-18 16:06 UTC by sovius23

2021-06-21 07:00 UTC, nikserg requested changes
Стоит доработать. Если будут вопросы, можем пообщаться в Телеграме, мой ник glndrwn

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +   const STATUS_NEW="New";
Не стоит пренебрегать форматированием кода. Если используешь IDE PhpStorm, там есть комбинация клавиш Ctrl+Alt+L, которая автоматически форматирует текущий файл по заданным правилам. По умолчанию они там плюс-минус соответствуют PSR.
Это важно, так как при работе в команде необходимо соблюдать стандарты форматирования.
Справедливо для всего кода в целом.

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +   private $statusMap=["New"=>"Новая","Aborted"=>"Отменена","In work"=>"В работе","Completed"=>"Выполнено","Failed"=>"Не выполнено"];
Здесь в качестве ключа нужно использовать константу, а не ее значение. Аналогично ниже.

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +         if($this->status=="New" or $this->status=="Failed"){
Общепринято использовать || по умолчанию, or только когда нужен именно этот оператор (приблизительно никогда)

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +   public function workerActions ($action,$workerId){
Доступные действия работника и заказчика можно объединить в одну функцию. Эта функция будет принимать ID пользователя в качестве аргумента и сравнивать его с clientId или с workerId. Таким образом можно понять, имеем мы дело с заказчиком или с исполнителем.

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +   private $userId,$workerId,$blackList=[];
Не очень понятно, что такое userId. Методом исключения можно предположить, что это ID заказчика. Тогда стоит назвать переменную более очевидно, например, clientId.
Непонятно, что такое blackList, зачем нужно это свойство.

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +      $this->userId=$userId;
Тут можно задать ID клиента, но где задать ID исполнителя?

2021-06-21 07:00 UTC, nikserg commented on Tasks/task3.php
> +?>
Часть задания - это сделать тестовый сценарий. Не вижу его в этом реквесте.

2021-06-30 08:00 UTC, nikserg requested changes
Не увидел никаких исправлений в соответствии с моими комментариями. Когда обрабатываешь комментарий - отвечай на него как-нибудь, можно просто типа "+" или "Исправил".

2021-07-27 14:08 UTC, oegir commented on test.php
> +require_once("Tasks\Task.php");
Разделитель "\" работает только под Windows, в то время как реальные сервера в большинстве случаев работают под Linux, в котором используется разделитель "/". Что бы код работал везде, php специально устроен так, что бы разделитель "/" в `require()` работал как под Windows, так и под Linux, старайтесь использовать его

2021-07-27 14:12 UTC, oegir commented
В данной ветке есть конфликт с файлом Readme.md . Сделайте merge ветки master в эту ветку, что бы разрешить конфликт

2021-07-29 06:31 UTC, merged